#!/bin/bash
# Diversity snap environment setup
# usage:  . my_snap2

export CALVALUS_INST=$PWD
export CALVALUS_SHARE=/home/cvop/share

export CALVALUS_PRODUCTION_JAR=$CALVALUS_SHARE/lib/calvalus-production-2.7-cawa-tool.jar
export CALVALUS_BEAM_VERSION=snap-7.0-SNAPSHOT
export CALVALUS_CALVALUS_VERSION=calvalus-2.15-diversity

export PYTHONPATH=$CALVALUS_INST:$CALVALUS_INST/lib:$CALVALUS_SHARE/lib:$PYTHONPATH
export PATH=$CALVALUS_INST:$CALVALUS_INST/bin:$CALVALUS_SHARE/bin:$PATH

PS1="\[\e]0;\u@\h: \w\a\]\[\e[1;32m\]\u \[\e[1;34m\]\w\[\e[0m\] \[\e[0;31m\](DIVERSITY_snap)\[\e[0m\]$ "

echo "using Calvalus      $CALVALUS_CALVALUS_VERSION"
echo "using SNAP          $CALVALUS_BEAM_VERSION"
echo "using DIVERSITY instance $CALVALUS_INST"
